### ISSUE TITLE
python 3.5 compatibility

### ISSUE THREAD

**Issue by jbogaardt** [jbogaardt/xlcompose#5]
eliminate f-strings to make xlcompose python3.5 compatible

**Comment by aegerton** [comment]
@jbogaardt thanks for your really prompt and helpful assistance.  However, a new error message has arisen, as follows;-
```
SyntaxError: invalid syntax (core.py, line 668)
```
Does this need a similar fix, please?

**Comment by aegerton** [comment]
@jbogaardt I see that line 668  also uses an f-string, but don't know enough to suggest a fix.  Sorry!

**Comment by jbogaardt** [comment]
yup, missed that one.  Releasing 0.1.10...

**Comment by jbogaardt** [comment]
Should be good now. did a double check and no other f-strings.  If you see something else, let me know.

**Comment by aegerton** [comment]
@jbogaardt You're a star!  It now runs just fine.  Thanks again for the really prompt and helpful support.  Don't you sleep?

**Comment by jbogaardt** [comment]
Glad all is working well.  8PM here, so not bed time yet.  Shout if you have any more questions or issues.
